### ISSUE TITLE
ArgumentError in Rails 4.2

### ISSUE THREAD

**Issue by askehansen** [mubi/persist_campaign#1]
I get this error in Rails 4.2 when calling redirect_to

```
ArgumentError: wrong number of arguments (2 for 0..1)
    from /Users/aske/.gem/ruby/2.2.0/gems/persist_campaign-0.0.1/lib/persist_campaign/controller.rb:11:in `_compute_redirect_to_location_with_persist_campaign_params'
    from /Users/aske/.gem/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_controller/metal/redirecting.rb:75:in `redirect_to'
    from /Users/aske/.gem/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_controller/metal/flash.rb:57:in `redirect_to'
    from /Users/aske/.gem/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:61:in `block in redirect_to'
    from /Users/aske/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/notifications.rb:164:in `block in instrument'
    from /Users/aske/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    from /Users/aske/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/notifications.rb:164:in `instrument'
    from /Users/aske/.gem/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:60:in `redirect_to'
    from /Users/aske/.gem/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_controller/metal/redirecting.rb:75:in `redirect_to'
```

**Comment by gtd** [comment]
Thanks for the report, it looks like the method signature was changed for Rails 4.2 by this commit: https://github.com/rails/rails/commit/2090615d

We are not yet on Rails 4.2, but we will be in due time at which point we'll provide a fix for this.  In the meantime PRs welcome ;)
